import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F6EBDD',
    alignItems: 'center',
  },
  safeArea: {
    flex: 1,
    width: '100%',
    maxWidth: 430,
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 112,
    gap: 22,
  },
  header: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFF7ED',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E4C8A8',
  },
  navIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    tintColor: '#5A351D',
  },
  signOutButton: {
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: '#F9E2D0',
    borderWidth: 1,
    borderColor: '#D08A5B',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  signOutButtonText: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#9A3F16',
    fontSize: 12,
    lineHeight: 16,
  },
  profileCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  profileLabel: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8A6A4E',
    fontSize: 12,
    lineHeight: 16,
  },
  profileName: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 15,
    lineHeight: 20,
  },
  heroCard: {
    minHeight: 202,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#8F3D12',
    padding: 24,
    justifyContent: 'flex-end',
  },
  heroPattern: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.24,
    resizeMode: 'cover',
  },
  heroEyebrow: {
    fontFamily: 'PlusJakartaSansSemiBold',
    color: '#3B210F',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  heroAmount: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#2B170B',
    fontSize: 42,
    lineHeight: 48,
  },
  heroMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#5A351D',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  formCard: {
    borderRadius: 8,
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#E4C8A8',
    padding: 18,
    gap: 14,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 20,
    lineHeight: 26,
  },
  sectionIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    tintColor: '#D96D22',
  },
  input: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#FBEEDC',
    borderWidth: 1,
    borderColor: '#E0BE95',
    color: '#4A2A16',
    paddingHorizontal: 16,
    fontFamily: 'PlusJakartaSansSemiBold',
    fontSize: 15,
  },
  selector: {
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: '#FBEEDC',
    borderWidth: 1,
    borderColor: '#E0BE95',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selectorIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: '#F2D3B2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorText: {
    flex: 1,
  },
  fieldLabel: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8A6A4E',
    fontSize: 12,
    lineHeight: 16,
  },
  fieldValue: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 15,
    lineHeight: 20,
  },
  selectorAction: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#B9571D',
    fontSize: 13,
    lineHeight: 18,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#8F3D12',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#FFF8EC',
    fontSize: 15,
    lineHeight: 20,
    includeFontPadding: false,
  },
  graphCard: {
    borderRadius: 8,
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#E4C8A8',
    padding: 16,
    gap: 12,
  },
  graphRow: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  graphMonthGroup: {
    gap: 7,
  },
  graphMonth: {
    width: 58,
    fontFamily: 'PlusJakartaSansBold',
    color: '#5A351D',
    fontSize: 12,
    lineHeight: 16,
  },
  graphTrack: {
    flex: 1,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#F2D3B2',
    overflow: 'hidden',
  },
  graphBar: {
    height: '100%',
    borderRadius: 6,
    backgroundColor: '#8F3D12',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  graphSegment: {
    height: '100%',
  },
  graphAmount: {
    width: 78,
    textAlign: 'right',
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#4A2A16',
    fontSize: 12,
    lineHeight: 16,
  },
  graphEmptyState: {
    paddingVertical: 6,
  },
  graphBreakdown: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingLeft: 68,
  },
  graphBreakdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  graphBreakdownDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  graphBreakdownText: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#6F523A',
    fontSize: 11,
    lineHeight: 14,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: -8,
  },
  sectionMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8A6A4E',
    fontSize: 13,
    lineHeight: 18,
  },
  filterList: {
    gap: 10,
    paddingRight: 22,
  },
  filterChip: {
    height: 42,
    borderRadius: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#E4C8A8',
  },
  filterChipSelected: {
    backgroundColor: '#5A351D',
    borderColor: '#5A351D',
  },
  filterText: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#8A6A4E',
    fontSize: 13,
    lineHeight: 18,
  },
  filterTextSelected: {
    color: '#FFF7ED',
  },
  expenseList: {
    gap: 18,
  },
  expenseGroup: {
    gap: 10,
  },
  expenseGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  expenseGroupTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 14,
    lineHeight: 20,
  },
  expenseGroupMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8A6A4E',
    fontSize: 12,
    lineHeight: 16,
  },
  expenseRow: {
    minHeight: 78,
    borderRadius: 8,
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#E4C8A8',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  expenseIconFrame: {
    width: 46,
    height: 46,
    borderRadius: 8,
    backgroundColor: '#F2D3B2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  expenseIcon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  expenseCopy: {
    flex: 1,
    gap: 3,
  },
  expenseTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 15,
    lineHeight: 20,
  },
  expenseCategory: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8A6A4E',
    fontSize: 12,
    lineHeight: 16,
  },
  expenseAmount: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#4A2A16',
    fontSize: 15,
    lineHeight: 20,
  },
  rowMenuButton: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#F2D3B2',
    borderWidth: 1,
    borderColor: '#DDB78B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowMenuButtonText: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#5A351D',
    fontSize: 16,
    lineHeight: 16,
    includeFontPadding: false,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  emptyCard: {
    borderRadius: 8,
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#E4C8A8',
    padding: 20,
  },
  emptyTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8A6A4E',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 4,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(61, 36, 19, 0.42)',
    justifyContent: 'flex-end',
  },
  modalPanel: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#E4C8A8',
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 34,
    gap: 14,
  },
  modalHandle: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#DDB78B',
    alignSelf: 'center',
    marginBottom: 6,
  },
  modalTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 22,
    lineHeight: 28,
  },
  modalSubtitle: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8A6A4E',
    fontSize: 13,
    lineHeight: 18,
    marginTop: -8,
  },
  actionGroup: {
    gap: 10,
  },
  dangerButton: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#F9E2D0',
    borderWidth: 1,
    borderColor: '#D08A5B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dangerButtonText: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#9A3F16',
    fontSize: 15,
    lineHeight: 20,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryOption: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#FBEEDC',
    borderWidth: 1,
    borderColor: '#E0BE95',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  categoryOptionSelected: {
    backgroundColor: '#D96D22',
    borderColor: '#D96D22',
  },
  categoryOptionIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  categoryOptionText: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#4A2A16',
    fontSize: 13,
    lineHeight: 18,
  },
  categoryOptionTextSelected: {
    color: '#FFF7ED',
  },
  pressed: {
    opacity: 0.78,
  },
});
