import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#09080D',
    alignItems: 'center',
  },
  safeArea: {
    flex: 1,
    width: '100%',
    maxWidth: 430,
  },
  keyboardView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 10,
    paddingBottom: 112,
    gap: 22,
  },
  header: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#18151F',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#292432',
  },
  navIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    tintColor: '#F9F4FF',
  },
  profileCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  profileLabel: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#8F879B',
    fontSize: 12,
    lineHeight: 16,
  },
  profileName: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 15,
    lineHeight: 20,
  },
  heroCard: {
    minHeight: 202,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#FF7A1A',
    padding: 24,
    justifyContent: 'flex-end',
  },
  heroPattern: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.24,
    resizeMode: 'cover',
  },
  heroEyebrow: {
    fontFamily: 'PlusJakartaSansSemiBold',
    color: '#2D1605',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  heroAmount: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#120902',
    fontSize: 42,
    lineHeight: 48,
  },
  heroMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#4A2508',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  formCard: {
    borderRadius: 8,
    backgroundColor: '#17141E',
    borderWidth: 1,
    borderColor: '#272230',
    padding: 18,
    gap: 14,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 20,
    lineHeight: 26,
  },
  sectionIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    tintColor: '#FF7A1A',
  },
  input: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#0F0D14',
    borderWidth: 1,
    borderColor: '#2B2534',
    color: '#F8F3FF',
    paddingHorizontal: 16,
    fontFamily: 'PlusJakartaSansSemiBold',
    fontSize: 15,
  },
  selector: {
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: '#0F0D14',
    borderWidth: 1,
    borderColor: '#2B2534',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selectorIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: '#211B29',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorText: {
    flex: 1,
  },
  fieldLabel: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#82788F',
    fontSize: 12,
    lineHeight: 16,
  },
  fieldValue: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 15,
    lineHeight: 20,
  },
  selectorAction: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#FF7A1A',
    fontSize: 13,
    lineHeight: 18,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#FF7A1A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#160B02',
    fontSize: 15,
    lineHeight: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: -8,
  },
  sectionMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#80778B',
    fontSize: 13,
    lineHeight: 18,
  },
  filterList: {
    gap: 10,
    paddingRight: 22,
  },
  filterChip: {
    height: 42,
    borderRadius: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#17141E',
    borderWidth: 1,
    borderColor: '#282331',
  },
  filterChipSelected: {
    backgroundColor: '#F8F3FF',
    borderColor: '#F8F3FF',
  },
  filterText: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#A9A0B5',
    fontSize: 13,
    lineHeight: 18,
  },
  filterTextSelected: {
    color: '#15101B',
  },
  expenseList: {
    gap: 18,
  },
  expenseGroup: {
    gap: 10,
  },
  expenseGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  expenseGroupTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 14,
    lineHeight: 20,
  },
  expenseGroupMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#80778B',
    fontSize: 12,
    lineHeight: 16,
  },
  expenseRow: {
    minHeight: 78,
    borderRadius: 8,
    backgroundColor: '#17141E',
    borderWidth: 1,
    borderColor: '#282331',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  expenseIconFrame: {
    width: 46,
    height: 46,
    borderRadius: 8,
    backgroundColor: '#231D2C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  expenseIcon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  expenseCopy: {
    flex: 1,
    gap: 3,
  },
  expenseTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 15,
    lineHeight: 20,
  },
  expenseCategory: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#82788F',
    fontSize: 12,
    lineHeight: 16,
  },
  expenseAmount: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#F8F3FF',
    fontSize: 15,
    lineHeight: 20,
  },
  rowMenuButton: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#211B29',
    borderWidth: 1,
    borderColor: '#332B3D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowMenuButtonText: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#F8F3FF',
    fontSize: 16,
    lineHeight: 16,
    includeFontPadding: false,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  emptyCard: {
    borderRadius: 8,
    backgroundColor: '#17141E',
    borderWidth: 1,
    borderColor: '#282331',
    padding: 20,
  },
  emptyTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'center',
  },
  emptyMeta: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#82788F',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 4,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    justifyContent: 'flex-end',
  },
  modalPanel: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: '#131018',
    borderWidth: 1,
    borderColor: '#2A2433',
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 34,
    gap: 14,
  },
  modalHandle: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#3A3245',
    alignSelf: 'center',
    marginBottom: 6,
  },
  modalTitle: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 22,
    lineHeight: 28,
  },
  modalSubtitle: {
    fontFamily: 'PlusJakartaSansMedium',
    color: '#82788F',
    fontSize: 13,
    lineHeight: 18,
    marginTop: -8,
  },
  actionGroup: {
    gap: 10,
  },
  dangerButton: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#241A1C',
    borderWidth: 1,
    borderColor: '#3B2729',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dangerButtonText: {
    fontFamily: 'PlusJakartaSansExtraBold',
    color: '#FF7A1A',
    fontSize: 15,
    lineHeight: 20,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryOption: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#1B1722',
    borderWidth: 1,
    borderColor: '#2B2534',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  categoryOptionSelected: {
    backgroundColor: '#FF7A1A',
    borderColor: '#FF7A1A',
  },
  categoryOptionIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  categoryOptionText: {
    fontFamily: 'PlusJakartaSansBold',
    color: '#F8F3FF',
    fontSize: 13,
    lineHeight: 18,
  },
  categoryOptionTextSelected: {
    color: '#160B02',
  },
  pressed: {
    opacity: 0.78,
  },
});
